#,-------------------------------------------------------------------------------------,
#| Tauri.toml - other app features                                                     |
#| - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - |
#| 1. Cargo reads Cargo.toml and calls Tauri                                           |
#| 2. Tauri reads Tauri.toml                                                           |
#'-------------------------------------------------------------------------------------'

# productName & version          ✅ INHERITED FROM CARGO
identifier = "davidbevi.watg"  # ❌ CANT INHERIT THIS FROM CARGO

[app]
withGlobalTauri = true

[app.security]
csp = "default-src 'self'; connect-src ipc: http://ipc.localhost"
capabilities = [ "default", "window-state" ]

[plugins.pluginReportTitle]
invoke = true
window-state = ""

[bundle]
active = true
targets = "all"
icon = [
  "src/icons/icon-watg.png",
  "src/icons/icon-watg.ico",
  "src/icons/tray-0.png",
  "src/icons/tray-1.png",
  "src/icons/tray-2.png",
  "src/icons/tray-3.png",
  "src/icons/tray-4.png",
  "src/icons/tray-5.png",
  "src/icons/tray-6.png",
  "src/icons/tray-7.png",
  "src/icons/tray-8.png",
  "src/icons/tray-9.png",
  "src/icons/tray-10.png",
]

[bundle.windows.webviewInstallMode]
type = "downloadBootstrapper"
